In [ ]:
import math 
import numpy as np
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving data_q4_q5.xlsx to data_q4_q5.xlsx


In [ ]:
def sigmoid(x):
  x = x.astype(float)
  z = np.exp(-x)
  sig = 1 / (1 + z)
  return sig

In [ ]:
def set(y):
    for i in range(len(y)):
        if(y[i]>0.5):
            y[i] = 1
        if(y[i]<0.5):
            y[i] = 0
    return y

In [ ]:
def set_type(y) :
  for i in range(len(y)):
        if(y[i] == 'M'):
            y[i] = 1
        if(y[i] == 'B'):
            y[i] = 0
  return y



In [ ]:
#def cost_function(X,y,w,reg):        ###define·cost·function·
  #  hypothesis = sigmoid(np.dot(X,w.T))   ###calculation·of·hypothesis·for·all·instances···
  #  J = -(1/len(y)) * ()
  #  return J

In [ ]:
#BCD for logistic regression 

def batch_gradient_descent(X,y,w,alpha,iters):
  
  cost_history = np.zeros(iters) # cost function for each iteration
  
  #initalize our cost history list to store the cost function on every iteration
  
  for i in range(iters):
    z = np.dot(X,w.T)
    hypothesis = sigmoid(z)
    w = w -  alpha * np.dot((hypothesis-y), X) #weight updation
  
  return w

In [ ]:
def stochastic_gradient_descent(X,y,w,alpha, iters):
  
  for i in range(iters):
    rand_index = np.random.randint(len(y))
    ind_x = X[rand_index:rand_index+1]
    ind_y = y[rand_index:rand_index+1]
    z = np.dot(ind_x,w.T)
    hypothesis = sigmoid(z)
    w = w - alpha * np.dot((hypothesis-ind_y), ind_x) 
  
  return w,

In [ ]:
def MB_gradient_descent(X,y,w,alpha, iters, batch_size):
  for i in range(iters):
    rand_index = np.random.randint(len(y))
    ind_x = X[rand_index:rand_index+batch_size]
    ind_y = y[rand_index:rand_index+batch_size]
    w = w - (alpha/batch_size) * (ind_x.T.dot(sigmoid(ind_x.dot(w)) - ind_y))
  
  return w

In [ ]:
# A function to implement min-max normalization
def norm(datan):
  data_min = np.min(datan, axis = 0)
  data_max = np.max(datan, axis = 0)
  datan = (datan- data_min)/(data_max-data_min)
  return datan


In [ ]:
data = pd.read_excel(uploaded['data_q4_q5.xlsx'])
#dataframe = data.drop(columns = 'diagnosis')

In [ ]:
df = data.sample(len(data)) #randomized sample
df = df.values
train_len = int(0.7 * len(data))

test_len = int(0.2 * len(data))

X_train = df[0: train_len,[i for i in range(30)]] 
X_test = df[train_len: train_len+test_len,[i for i in range(30)]]     #test
X_vald = df[train_len+test_len:,[i for i in range(30)]]                 #validation
l = len(X_train)
m = len(X_test)
n = len(X_vald) 


y_train = df[0: train_len,30]                    #train
y_test = df[train_len: train_len+test_len,30]     #test
y_vald = df[train_len+test_len:,30] #val

In [ ]:
X_train = norm(X_train)
X_test = norm(X_test)     #test
X_vald = norm(X_vald)               #validation

In [ ]:
X_train = np.append(np.ones([l, 1]),X_train, axis=1) #Column of ones
X_test = np.append(np.ones([m, 1]),X_test, axis=1) #Column of ones
X_vald = np.append(np.ones([n, 1]),X_vald, axis=1) #Column of ones

In [ ]:
X_train[0]

array([1.0, 0.2443312601008864, 0.5744771660264618, 0.24701110162254483,
       0.14111483294683502, 0.49251660224006344, 0.365796863228546,
       0.2642924086223055, 0.34160039761431416, 0.4267676767676768,
       0.35375055481580125, 0.11370631902951293, 0.18073727015558697,
       0.10224756160768977, 0.05716675854571529, 0.20627528299962603,
       0.1819629284705741, 0.09786043449637918, 0.3284950343773873,
       0.1580499458733062, 0.12865102304708298, 0.34402093898249625,
       0.6051341217190654, 0.3278416566557977, 0.20717491584590447,
       0.7523608267846529, 0.36752335768547895, 0.321405750798722,
       0.5896907216494846, 0.4319315751960085, 0.31523022432113346],
      dtype=object)

In [ ]:
y_train

array(['M', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B',
       'B', 'M', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'M', 'B', 'M', 'B',
       'M', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'M', 'M', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'M', 'M',
       'B', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'M', 'B', 'B', 'M', 'B',
       'B', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B',
       'B', 'B', 'B', 'M', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'M', 'B',
       'B', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'M', 'M', 'B', 'B',
       'B', 'M', 'M', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'M',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'M', 'B', 'M',
       'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'M', 'B',
       'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B

In [ ]:
X_train.shape

(398, 31)

In [ ]:
y_test = set_type(y_test)
y_train = set_type(y_train)
y_vald = set_type(y_vald)

In [ ]:
y_train

array([1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,

In [ ]:
alpha=0.005
iters=500
w= np.zeros((X_train.shape[1])) ###weight initialization
w_BCD = batch_gradient_descent(X_train,y_train,w,alpha,iters)
print(w_BCD)

[-9.938069827186878 0.8951614744746299 2.088418078176403 0.977901778510686
 1.4716923721479214 0.7178860316271198 0.33871809152230326
 3.078331589531312 4.1803988902237545 -0.03578783521443474
 -2.799967812137131 2.7893960634013157 0.3447398665342109
 2.0471847078355467 1.8819162302390373 -0.17916063436683838
 -1.371418484402272 -0.6443426388828907 0.2562349294318265
 -0.5255638699504118 -1.4147616123139855 2.918546848169572
 2.874463877189223 2.51366278507917 3.007390549099292 1.4185386430975444
 0.37558709610872115 1.711211189714206 3.8000024798188137
 1.3281800153591738 -0.23384586139783037]


In [ ]:
y_pred = sigmoid(np.dot(X_test,w_BCD.T))
y_pred = set(y_pred)

In [ ]:
y_pred

array([1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1.,
       1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 0.,
       0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1.,
       1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0.,
       0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1.])

In [ ]:
y_actual = pd.Series(y_test, name='Actual')
y_pred = pd.Series(y_pred, name='Predicted')

In [ ]:
confmat = pd.crosstab(y_actual, y_pred)
print(confmat)
confmat = np.asarray(confmat)
tp = confmat[1][1]
tn = confmat[0][0]
fp = confmat[0][1]
fn = confmat[1][0]

Predicted  0.0  1.0
Actual             
0           56    5
1            1   51


In [ ]:
Acc = (tp+tn)/(tp+tn+fp+fn)
SE = tp/(tp+fn)
SP = tn/(tn+fp)
print('Accuracy = ',Acc)
print('Sensitivity = ',SE)
print('specificity = ',SP)

Accuracy =  0.9469026548672567
Sensitivity =  0.9807692307692307
specificity =  0.9180327868852459


In [ ]:
#Logistic regression with socastic gradient descent
alpha=0.005
iters=500
w= np.zeros((X_train.shape[1])) ###weight initialization
w_SGD = stochastic_gradient_descent(X_train,y_train,w,alpha,iters)
w_SGD = np.array(w_SGD)
print(w_SGD)

[[-0.31349653456717086 0.04592714133948313 -0.029469242832653023
  0.049529138714109806 0.05909478758599255 -0.051015081669462135
  0.03477597283347468 0.08587491523142753 0.09861083088102914
  -0.06521295400398364 -0.10022118892670437 0.03487356122985107
  -0.05053817239240319 0.032252579915281236 0.03540893958866682
  -0.05662538485403935 -0.006916069753025564 -0.0033792124178667884
  -0.013394302215421311 -0.06638712000238434 -0.030594232858995592
  0.08139454806587208 -0.02308790931263196 0.08114333062394326
  0.08880545608052351 -0.05520242143033854 0.03463316194119539
  0.05562595154882657 0.08373072515231177 -0.025710307844776323
  -0.02327390553730539]]


In [ ]:
w_SGD = np.squeeze (w_SGD)
print(w_SGD)

[-0.31349653456717086 0.04592714133948313 -0.029469242832653023
 0.049529138714109806 0.05909478758599255 -0.051015081669462135
 0.03477597283347468 0.08587491523142753 0.09861083088102914
 -0.06521295400398364 -0.10022118892670437 0.03487356122985107
 -0.05053817239240319 0.032252579915281236 0.03540893958866682
 -0.05662538485403935 -0.006916069753025564 -0.0033792124178667884
 -0.013394302215421311 -0.06638712000238434 -0.030594232858995592
 0.08139454806587208 -0.02308790931263196 0.08114333062394326
 0.08880545608052351 -0.05520242143033854 0.03463316194119539
 0.05562595154882657 0.08373072515231177 -0.025710307844776323
 -0.02327390553730539]


In [ ]:
y_pred = sigmoid(np.dot(X_test,w_SGD.T))
y_pred = set(y_pred)


In [ ]:
y_pred

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
y_actual = pd.Series(y_test, name='Actual')
y_pred = pd.Series(y_pred, name='Predicted')


In [ ]:
confmat = pd.crosstab(y_actual, y_pred)
print(confmat)
confmat = np.asarray(confmat)
tp = confmat[1][1]
tn = confmat[0][0]
fp = confmat[0][1]
fn = confmat[1][0]
Acc = (tp+tn)/(tp+tn+fp+fn)
SE = tp/(tp+fn)
SP = tn/(tn+fp)
print('Accuracy = ',Acc)
print('Sensitivity = ',SE)
print('specificity = ',SP)

Predicted  0.0  1.0
Actual             
0           61    0
1           42   10
Accuracy =  0.6283185840707964
Sensitivity =  0.19230769230769232
specificity =  1.0


In [ ]:
alpha=0.005
iters=500
batch_size = 30
w= np.zeros((X_train.shape[1])) ###weight initialization
w_MBGD = MB_gradient_descent(X_train,y_train,w,alpha,iters,batch_size)
print(w_MBGD)


[-0.2922359886027979 0.046326282625936036 -0.024952982074459663
 0.04959415906732672 0.05835255748879707 -0.04014953372485376
 0.03193938566682174 0.08548327852325091 0.09803174164268283
 -0.05970971105524067 -0.08723790567671012 0.0387879546442997
 -0.04540592417977377 0.035298406169141296 0.03823131596553538
 -0.050577430031411325 -0.005798488329350273 0.0008447994355502685
 -0.007388553886715478 -0.05984671198525166 -0.02511388207026195
 0.07801645767621608 -0.020492954467550395 0.07712780038044803
 0.08465457465320876 -0.04571811333382822 0.026336244059559297
 0.05370824098656535 0.0811598779832903 -0.028746874880265824
 -0.0192961626569748]


In [ ]:
y_pred = sigmoid(np.dot(X_test,w_SGD.T))
y_pred = set(y_pred)
y_actual = pd.Series(y_test, name='Actual')
y_pred = pd.Series(y_pred, name='Predicted')
confmat = pd.crosstab(y_actual, y_pred)
print(confmat)
confmat = np.asarray(confmat)
tp = confmat[1][1]
tn = confmat[0][0]
fp = confmat[0][1]
fn = confmat[1][0]
Acc = (tp+tn)/(tp+tn+fp+fn)
SE = tp/(tp+fn)
SP = tn/(tn+fp)
print('Accuracy = ',Acc)
print('Sensitivity = ',SE)
print('specificity = ',SP)

Predicted  0.0  1.0
Actual             
0           61    0
1           42   10
Accuracy =  0.6283185840707964
Sensitivity =  0.19230769230769232
specificity =  1.0
